### PR TITLE
fix: inaccurate headers

### LINKED ISSUE #29: Fix inaccurate headers
We're decrementing values too late(once we send the request) and the user will see the incorrect values in the response's headers

### PR DESCRIPTION
**Pull request by TMaszko**
Closes #29
We're delaying setting the `remaining` header value till `onSend` hook is called and after the store decrements value for the specific key.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -83,6 +67,27 @@ const slowDownPlugin = async (fastify, settings) => {
       return reply
     }
   })
+
+  fastify.addHook('onSend', async (req, reply) => {
+    const key = options.keyGenerator(req)
+    if (options.skipFailedRequests) {
+      if (reply.statusCode >= 400) {
```
Comment (simoneb) [inline index.js:74]: how about we merge these two conditions in a single if? :)

Comment (ilteoood) [reply index.js:74]: +1

**Review by ilteoood — CHANGES_REQUESTED** [review]

File: test/skip-options.test.js [hunk 2]
```diff
@@ -58,41 +58,68 @@ t.test('should not apply the delay header', async t => {
     })
     t.teardown(() => fastify.close())
 
+    const test = {
```
Comment (ilteoood) [inline test/skip-options.test.js:61]: why an object and not a simple counter?

File: test/skip-options.test.js [hunk 3]
```diff
@@ -58,41 +58,68 @@ t.test('should not apply the delay header', async t => {
...
+    'if skipSuccessfulRequests is true and the request succeeds and one fail it updates remaining header value properly',
     async t => {
       const fastify = Fastify()
       await fastify.register(slowDownPlugin, {
         skipSuccessfulRequests: true
       })
       t.teardown(() => fastify.close())
-
-      fastify.get('/', async () => 'Hello from fastify-slow-down!')
+      let test = {
```
Comment (ilteoood) [inline test/skip-options.test.js:97]: same as above

File: test/skip-options.test.js (hunk 2 above)
Comment (TMaszko) [reply test/skip-options.test.js:61]: because closure will remember the value when it is created :). However it's not the case when you are using references

File: index.js [hunk 4]
```diff
@@ -83,6 +67,27 @@ const slowDownPlugin = async (fastify, settings) => {
...
+        await store.decrementOnKey(key)
+        if (options.headers && req.slowDown.remaining < options.delayAfter) {
+          reply.header(HEADERS.remaining, req.slowDown.remaining + 1)
+        }
+      }
+    }
+
+    if (options.skipSuccessfulRequests) {
+      if (reply.statusCode < 400) {
+        await store.decrementOnKey(key)
```
[the remark this answers is not in the document]
Comment (RomuloVitoi) [reply index.js]: or even combine the ifs

**Review by simoneb — APPROVED** [review]

**Review by RomuloVitoi — APPROVED** [review]

**Review by ilteoood — APPROVED** [review]
