### PR TITLE
fix: reset whole store instead of a specific part of it

### LINKED ISSUE #21: Whole store is being reset
Current behaviour: We're reseting the whole store once time interval passes.
Desired behaviour: We should reset only the specific request after time interval for that specific request passes

### PR DESCRIPTION
**Pull request by TMaszko**
Closes #21

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
I'm not convinced this is a robust implementation, as it uses a timer for each single key. how about a single timer which evicts multiple keys periodically instead?

**Comment by TMaszko** [comment]
Hmm.. Good idea ;) How often it should check for the expired keys ?

**Comment by TMaszko** [comment]
@simoneb I think we can use https://github.com/avoidwork/tiny-lru because it doesn't make sense to implement it on our own

**Comment by simoneb** [comment]
> @simoneb I think we can use https://github.com/avoidwork/tiny-lru (like fastify-rate-limit did) because it doesn't make sense to implement it on our own

agreed

File: lib/store.js [hunk 1]
```diff
@@ -1,24 +1,38 @@
...
-    this.resetStore()
-    this.interval = setInterval(() => this.resetStore(), timeWindowMs)
-  }
-
-  resetStore() {
-    this.hits = {}
+    this.cache = lru(cacheSize, timeWindowMs)
+    this.interval = setInterval(() => {
+      this.cache.keys().forEach(key => {
+        this.cache.get(key) // it deletes expired keys under the hood and returns undefined
```
Comment (ilteoood) [inline lib/store.js:13]: I've not found this behaviour in the library documentation, so I don't think its safe to use this assumpion

Comment (TMaszko) [reply lib/store.js:13]: `fastify-rate-limit` plugin bases on this behaviour so I assumed that we can take advantage of it as well

Comment (TMaszko) [reply lib/store.js:13]: Additionaly this is the only way to interact with `items` directly and check whether item has expired or not

File: index.js [hunk 2]
```diff
@@ -7,14 +7,20 @@ import { convertToMs, calculateDelay } from './lib/helpers.js'
 
 const slowDownPlugin = async (fastify, settings) => {
   const options = { ...DEFAULT_OPTIONS, ...settings }
-  const store = new Store(convertToMs(options.timeWindow))
+  const store = new Store(
+    convertToMs(options.timeWindow),
+    convertToMs(options.intevalTimeExpiredKeys),
```
Comment (mahenrique94) [inline index.js:12]: Maybe should be `intervalTimeExpiredKeys`, I believe there is a typo here.

File: lib/store.js (hunk 1 above)
Comment (mahenrique94) [inline lib/store.js:13]: Why don't use a `delete`,  `remove` or `clear` (or similar) method to be more semantic? It's pretty weird using a `get` function as deleting, if one day this behavior has been changed will crash the code (making the code very sensible).

Comment (TMaszko) [reply lib/store.js:13]: There is no other way to delete the key when it is expired. Otherwise we will have to use `items` property directly which is not exposed.

File: index.js (hunk 2 above)
Comment (TMaszko) [reply index.js:12]: Yep ;) Good catch !

**Review by simoneb — CHANGES_REQUESTED** [review]
there are no docs updates

File: lib/constants.js [hunk 3]
```diff
@@ -1,6 +1,8 @@
 export const DEFAULT_OPTIONS = {
   delayAfter: 5,
+  cacheSize: 5000,
   delay: '1 second',
+  intervalTimeExpiredKeys: '15 minutes',
```
Comment (simoneb) [inline lib/constants.js:5]: rename as per previous comment

File: lib/store.js [hunk 4]
```diff
@@ -1,24 +1,38 @@
+import { lru } from 'tiny-lru'
+import { DEFAULT_OPTIONS } from './constants.js'
 export class Store {
-  constructor(timeWindowMs) {
+  constructor(
+    timeWindowMs,
+    intervalTimeExpiredKeysEvictionMs,
+    cacheSize = DEFAULT_OPTIONS.cacheSize
```
Comment (simoneb) [inline lib/store.js:7]: don't apply defaults here. apply them only when parsing the options in the plugin initialization. this class shouldn't know anything about default values

File: lib/store.js [hunk 5]
```diff
@@ -1,24 +1,38 @@
...
     this.timeWindowMs = timeWindowMs
-    this.resetStore()
-    this.interval = setInterval(() => this.resetStore(), timeWindowMs)
-  }
-
-  resetStore() {
-    this.hits = {}
+    this.cache = lru(cacheSize, timeWindowMs)
+    this.interval = setInterval(() => {
+      this.cache.keys().forEach(key => {
```
Comment (simoneb) [inline lib/store.js:12]: Seeing we've now switched to using tiny-lru, I don't quite understand why we're doing this then. why don't we just leave to the cache the responsibility to remove entries based on its internal logic?

**Review by simoneb — COMMENTED** [review]
I have some doubts about the relevance and need for the cache expire internal

File: README.md [hunk 6]
```diff
@@ -39,29 +39,31 @@ await fastify.listen({ port: 3000 })
...
+| timeWindow              | string \|, number | 30 seconds      | The duration of the time window during which request counts are kept in memory. It can be expressed in milliseconds or as a string in [`ms`](https://github.com/zeit/ms) format. Set to `0` to disable delaying.                               |
+| cacheSize               | number            | 5000            | The maximum number of items that will be stored in the in-memory cache _(this plugin internally uses a lru cache to handle the clients, you can change the size of the cache with this option)_                                                |
+| intervalTimeExpiredKeys | number \| string  | 15 minutes      | The duration of the interval that will clear out the cache from the expired keys                                                                                                                                                               |
```
[the remark this answers is not in the document]
Comment (TMaszko) [reply README.md:57]: Maybe it should have a better name like `inMemoryCacheSize`?

File: lib/store.js (hunk 5 above)
Comment (simoneb) [reply lib/store.js:12]: but that's the job of the cache library we use to take care of that, so I think this is an unnecessary optimization we're doing, which complicates the implementation without good reason, while also introducing a new fairly obscure option. let's remove this and the option please

File: index.d.ts [hunk 7]
```diff
@@ -6,6 +6,7 @@ import {
 
 type FastifySlowDownOptions = {
   delay?: string | number
+  inMemoryCacheSize?: string | number
```
Comment (simoneb) [inline index.d.ts:9]: why does this allow a string too?

File: test/reset-delay.test.js [hunk 8]
```diff
@@ -7,16 +7,23 @@ import { internalFetch, slowDownAPI } from './helpers.js'
...
-  const fastify = Fastify()
-  const clock = FakeTimers.install()
+let fastify = null
+let clock = null
+
+const APP_RESPONSE_TEXT = 'Hello from the fastify-slow-down plugin'
+
+beforeEach(async t => {
+  fastify = Fastify()
+  clock = FakeTimers.install()
```
Comment (simoneb) [inline test/reset-delay.test.js:17]: these tests will fail unexpectedly because tap runs them in parallel. this was already a problem before, so let's avoid this pattern altogether. each test must instantiate its own fastify. if there is common set up to do (e.g. plugin registration and run configuration) we can consider factoring it into a function which we execute within each test, otherwise let's keep it simple and have each test instantiate fastify

**Review by simoneb — CHANGES_REQUESTED** [review]

**Review by simoneb — APPROVED** [review]
